# Le perceptron Multi-Classes

In [1]:
import numpy as np

class mPerceptron:
    def __init__(self,inputs,targets):
        
        self.inputs = inputs
        self.targets = targets
        
        #Nombre de perceptrons
        if np.ndim(inputs) > 1:
            self.inNums = np.shape(inputs)[1]
        else:
            self.inNums = 1
            
        if np.ndim(targets) > 1:
            self.outNums = np.shape(targets)[1]
        else:
            self.outNums = 1
            
        self.dataNums = np.shape(inputs)[0]
        
        #Initialisation des poids
        self.weights = np.random.rand(self.inNums +1,self.outNums)*0.1-0.05
        
        #Normalisation (Ajout du biais)
        self.inputs = np.concatenate((inputs,-np.ones((self.dataNums,1))),axis=1)
        
    def activationFun(self):
        self.activations = np.dot(self.inputs,self.weights)
        return np.where(self.activations>0,1,0)
    
    def train(self,lRate,iterationsNums):
        
        for i in range(iterationsNums + 1):
            activations = self.activationFun()
            self.weights -= lRate*np.dot(np.transpose(self.inputs),activations-self.targets)
    

        
    def test(self,inputs,targets):
        #Normalisation pour inclure le calcul du biais
        inputs = np.concatenate((inputs,np.ones((np.shape(inputs)[0],1))),axis=1)
        
        outputs = np.dot(inputs,self.weights)
        classesNums = np.shape(targets)[1]
        
        if(classesNums == 1):
            classesNums = 2
            outputs = np.where(outputs >0,1,0)
        else:
            outputs = np.argmax(outputs,1)
            targets = np.argmax(targets,1)
            
        cMatrix = np.zeros((classesNums,classesNums))
        
        for i in range(classesNums):
            for j in range(classesNums):
                cMatrix[i,j] = np.sum(np.where(outputs == i,1,0)*np.where(targets == j,1,0))
                
        
        precision = np.trace(cMatrix)/np.sum(cMatrix)
        
        return (cMatrix,precision)
    
    
    def predict(self,inputs):
        
        inputs = np.concatenate((inputs,np.ones((np.shape(inputs)[0],1))),axis=1)
        
        outputs = np.dot(inputs,self.weights)
        classesNums = np.shape(self.targets)[1]
        
        if(classesNums == 1):
            classesNums = 2
            outputs = np.where(outputs >0,1,0)
        else:
            outputs = np.argmax(outputs,1)
            
        return outputs
              
    
        
        
        

# Récupération des données

In [2]:
import numpy as np
import csv


data = []
for k in range(10):
   
    with open('otto%i.csv'%k, 'rb') as trainFile:
        reader = csv.reader(trainFile)
        i = 0
        reader.next()
        for r in reader:
            data.append((np.array((r[:len(r) - 1])).astype(float),np.array(r[len(r) - 1]).astype(float).astype(int)))

        
            
print len(data)




61820


# Entrainement du classifieur

In [3]:
datanum = len(data)
trainData = data[:datanum - datanum/10]
        
trainFeatures = np.array([x for x,_ in trainData])
trainClasses = np.array([c for _,c in trainData]) 

classesNum = len(set(trainClasses))
featuresNum = trainFeatures.shape[0]

trainTargets = np.zeros((featuresNum,classesNum))

for i in range(featuresNum):
    trainTargets[i,trainClasses[i]] = 1

p = mPerceptron(trainFeatures,trainTargets)
p.train(0.2,100)


# Premier test

In [4]:
testData = data[datanum - datanum/10:datanum]

    
testFeatures = np.array([x for x,_ in testData])
testClasses = np.array([c for _,c in testData]) 

testclassesNum = len(set(trainClasses))
testfeaturesNum = testFeatures.shape[0]

testTargets = np.zeros((testfeaturesNum,testclassesNum))

for i in range(testfeaturesNum):
    testTargets[i,testClasses[i]] = 1
    
p.test(testFeatures,testTargets)


(array([[  4.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  4.80000000e+01,   1.59700000e+03,   7.69000000e+02,
           2.36000000e+02,   5.20000000e+01,   6.00000000e+01,
           1.02000000e+02,   3.60000000e+01,   4.50000000e+01],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   3.00000000e+00,   1.40000000e+01,
           1.70000000e+01,   0.00000000e+00,   4.00000000e+00,
           7.00000000e+00,   0.00000000e+00,   1.00000000e+00],
        [  2.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   2.19000000e+02,   0.00000000e+00,
           1.00000000e+00,   1.00000000e+00,   0.00000000e+00],
        [  9.00000000e+00,   0.00000000e+00,   0.0

In [10]:
from sklearn import svm

clf = svm.SVC()
clf.fit(trainFeatures[:10000],trainClasses[:10000])
x = clf.predict(testFeatures[:10])

print x
print testClasses[:10]


[0 0 0 8 8 1 0 0 7 7]
[0 0 0 0 0 0 0 0 0 0]


# Developpement

In [ ]:
divInd =  datanum/10
devData = data[datanum - 2*divInd:datanum - divInd]
data = np.concatenate((data[:datanum - 2*datanum/10],data[datanum - datanum/10:datanum]),axis=0)






In [ ]:
trainData = data[:len(data) - len(data)/10]

trainFeatures = np.array([x for x,_ in trainData])
trainClasses = np.array([c for _,c in trainData]) 

classesNum = len(set(trainClasses))
featuresNum = trainFeatures.shape[0]

trainTargets = np.zeros((featuresNum,classesNum))

for i in range(featuresNum):
    trainTargets[i,trainClasses[i]] = 1
    
    
testData = data[len(data)- len(data)/10:len(data)]

    
testFeatures = np.array([x for x,_ in testData])
testClasses = np.array([c for _,c in testData]) 

testclassesNum = len(set(trainClasses))
testfeaturesNum = testFeatures.shape[0]

testTargets = np.zeros((testfeaturesNum,testclassesNum))

for i in range(testfeaturesNum):
    testTargets[i,testClasses[i]] = 1
    

alphas = np.array([float(i)/10 for i in range(1,10)])
precisions = np.zeros(alphas.shape[0])
p = mPerceptron(trainFeatures,trainTargets)

for i in range(20):
    for a in alphas:
        p.train(a,20)
        cm,pr = p.test(testFeatures,testTargets)
        precisions[np.where(alphas == a)] += pr

precisions /=19
    
print alphas[precisions.argmax()]



# La Cross-Validation

In [ ]:
precisions = np.zeros(9)
for j in range(9):
    trainData = np.concatenate((data[:divInd*j],data[divInd*j+divInd:]))
    testData = data[divInd*j:divInd*j+divInd]
    
    trainFeatures = np.array([x for x,_ in trainData])
    trainClasses = np.array([c for _,c in trainData]) 

    classesNum = len(set(trainClasses))
    featuresNum = trainFeatures.shape[0]

    trainTargets = np.zeros((featuresNum,classesNum))

    for i in range(featuresNum):
        trainTargets[i,trainClasses[i]] = 1

    p = mPerceptron(trainFeatures,trainTargets)
    p.train(0.1,20)
    
    testFeatures = np.array([x for x,_ in testData])
    testClasses = np.array([c for _,c in testData]) 

    testclassesNum = len(set(trainClasses))
    testfeaturesNum = testFeatures.shape[0]

    testTargets = np.zeros((testfeaturesNum,testclassesNum))

    for i in range(testfeaturesNum):
        testTargets[i,testClasses[i]] = 1

    cm,pr = p.test(testFeatures,testTargets)
    precisions[j] = pr


In [ ]:
print np.mean(precisions)